automation@1.0.0 cypress-test-headless
> npx cypress run



DevTools listening on ws://127.0.0.1:34589/devtools/browser/36a520fa-83fa-4910-a970-6cc9212db840

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        15.7.0                                                                         │
  │ Browser:        Electron 138 (headless)                                                        │
  │ Node Version:   v22.13.1 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          1 found (openCart.cy.js)                                                       │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  openCart.cy.js                                                                  (1 of 1)


  Registration Flow
    √ Enter the form details (5200ms)


  1 passing (13s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     13 seconds                                                                       │
  │ Spec Ran:     openCart.cy.js                                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  openCart.cy.js                           00:13        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    √  All specs passed!                        00:13        1        1        -        -        -
